config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
      get '/like', to: 'posts#like', as: :like
      get '/unlike', to: 'posts#unlike', as: :unlike
    end
  end
  devise_for :users

  get '/users', to: 'users#index', as: :users
  get '/:id', to: 'users#show', as: :user
  get '/:id/request', to: 'users#request_friendship', as: :request
  get '/:id/accept', to: 'users#accept_friendship', as: :accept
  get '/:id/decline', to: 'users#decline_fiendship', as: :decline
  get '/:id/unfriend', to: 'users#remove_friendship', as: :unfriend



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

app/models/liking.rb
class Liking < ApplicationRecord
  belongs_to :liked_post, class_name: 'Post'
  belongs_to :liker, class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  has_many :comments, dependent: :destroy
  has_many :likings, foreign_key: :liked_post_id, dependent: :destroy
  has_many :likers, through: :likings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_friendship
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likings, foreign_key: :liker_id
  has_many :liked_posts, through: :likings
  has_many :friend_requests_as_requestor, foreign_key: :requestor_id, class_name: 'FriendRequest'
  has_many :friend_requests_as_receiver, foreign_key: :receiver_id, class_name: 'FriendRequest'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: "Your comment was posted"
    else
      redirect_to post_path(@post), alert: "Your comment could not be posted"
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), notice: "Your comment was deleted"
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/likings_controller.rb
class LikingsController < ApplicationController


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = current_user.posts.new
    @posts = Post.where(user_id: current_user.friends).or(Post.where(user_id: current_user)).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: "Your post was created"
    else
      render :new, alert: "Your post was not created"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_back fallback_location: posts_path, notice: "Your post was updated"
    else
      render :edit, notice: "Something went wrong. Please try again."
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "Your post was deleted"
  end

  def like
    @post = Post.find(params[:id])
    @post.likers << current_user
    redirect_back fallback_location: posts_path
  end

  def unlike
    @post = Post.find(params[:id])
    @post.likers.delete(current_user)
    redirect_back fallback_location: posts_path
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def request_friendship
    requested_user = User.find_by_id(params[:id])
    current_user.friend_request(requested_user)
    redirect_to users_path, notice: "Your friend request was sent to #{requested_user.name}"
  end

  def accept_friendship
    requesting_user = User.find_by_id(params[:id])
    current_user.accept_request(requesting_user)
    redirect_to users_path, notice: "You and #{requesting_user.name} are now friends"
  end

  def decline_fiendship
    requesting_user = User.find_by_id(params[:id])
    current_user.decline_request(requesting_user)
    redirect_to users_path, notice: "You ignored the request from #{requesting_user.name}"
  end

  def remove_friendship
    other_user = User.find_by_id(params[:id])
    current_user.remove_friend(other_user)
    redirect_to users_path, notice: "You and #{other_user.name} are no longer friends"
  end

  def others
    User.where_not(current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likings_helper.rb
module LikingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ], local: true do |f| %>
  <div class="input-group">
    <%= f.text_field :body, placeholder: "Write a comment", class: "form-control" %>
    <div class="input-group-append">
      <%= f.submit 'Post', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-white shadow-sm">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fab fa-facebook text-primary fa-lg"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        </li>
      </ul>
      <span class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to "Account", edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="row">
  <nav class="nav flex-column">
    <%= link_to posts_path, class: "nav-link" do %>
    <h6 class="text-dark"><i class="fas fa-th-large text-primary fa-lg mr-2"></i> Posts </h6>
    <% end %>
    <%= link_to users_path, class: "nav-link" do %>
    <h6 class="text-dark"><i class="fas fa-user-friends text-primary fa-lg mr-1"></i> Friends </h6>
    <% end %>
    <%= link_to user_path(current_user), class: "nav-link" do %>
    <h6 class="text-dark"><i class="fas fa-user-circle text-primary fa-lg mr-2"></i> Profile  </h6>
    <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body class="mb-5">
    <%= render 'layouts/navbar' %>
    <% if signed_in? %>
      <div class="container mt-5">
        <%= render_flash_messages dismissible: true %>
        <div class="row">
          <div class="col-md-3">
            <%= render 'layouts/sidebar' %>
          </div>
          <div class="col-md-9">
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %>
    <div class="container mt-5">
      <%= yield %>
    </div>
    <% end %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% @post.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "What's on your mind?", class: "form-control" %>
  </div>
<%= f.submit class: "btn btn-block btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1 class="mb-4">Edit Post</h1>
<div class="card shadow-sm">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<h1 class="mb-4">Recent Posts</h1>
<div class="card shadow-sm">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

<% @posts.each do |post| %>
  <div class="card shadow-sm mt-3">
    <div class="card-body">
      <%= link_to post.user.name, user_path(post.user), class: "h5 d-inline text-dark text-decoration-none" %>
      <% if post.user == current_user %>
        <a class="float-right" data-toggle="dropdown" href="#" role="button"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-h text-muted"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to 'Edit', edit_post_path(post), class: "dropdown-item" %>
          <%= link_to 'Delete', post_path(post), method: :delete, class: "dropdown-item",
              data: { confirm: "Are you sure?"}%>
        </div>
      <% end %>

      <p class="small"> <%= post.created_at.strftime('%b %e at %l:%M %p') %> </p>
      <p> <%= post.body %> </p>

      <hr>

      <% if post.likers.include?(current_user) %>
        <%= link_to unlike_post_path(post), class: "text-decoration-none text-dark" do %>
          <i class="fas fa-thumbs-up text-primary"></i> <%= pluralize(post.likers.count, 'like') %>
        <% end %>
      <% else %>
        <%= link_to like_post_path(post), class: "text-decoration-none text-dark" do %>
          <i class="far fa-thumbs-up"></i> <%= pluralize(post.likers.count, 'like') %>
          <% end %>
      <% end %>

      <%= link_to "#{pluralize(post.comments.count, 'comment')}", post_path(post),
      class: "text-muted float-right" %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<div class="card shadow-sm">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card shadow-sm mt-3">
  <div class="card-body">
    <h5 class="d-inline"> <%= @post.user.name %> </h5>
    <% if @post.user == current_user %>
      <a class="float-right" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-h text-muted"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <%= link_to 'Edit', edit_post_path(@post), class: "dropdown-item" %>
        <%= link_to 'Delete', post_path(@post), method: :delete, class: "dropdown-item",
            data: { confirm: "Are you sure?"}%>
      </div>
    <% end %>

    <p class="small"> <%= @post.created_at.strftime('%b %e at %l:%M %p') %> </p>
    <p class="mb-4"> <%= @post.body %> </p>
    <hr>
    <% if @post.likers.include?(current_user) %>
      <%= link_to unlike_post_path(@post), class: "text-decoration-none text-dark" do %>
        <i class="fas fa-thumbs-up text-primary"></i> <%= pluralize(@post.likers.count, 'like') %>
      <% end %>
    <% else %>
      <%= link_to like_post_path(@post), class: "text-decoration-none text-dark" do %>
        <i class="far fa-thumbs-up"></i> <%= pluralize(@post.likers.count, 'like') %>
        <% end %>
    <% end %>
  </div>



  <div class="card-footer pb-4 pt-4">
    <% if @post.comments.any? %>
      <% @post.comments.each do |comment| %>
        <p>
          <%= link_to comment.user.name, user_path(comment.user), class: "h6 text-dark" %>
          <%= comment.body %>
          <% if comment.user == current_user %>
            <%= link_to [comment.post, comment], method: :delete do %>
              <i class="far fa-trash-alt text-muted text-decoration-none float-right"></i>
            <% end %>
          <% end %>
        </p>
      <% end %>
    <% end %>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-6">
      <h1> Friends </h1>
    </div>
    <div class="col-md-6">
      <ul class="nav nav-pills mb-3 float-right" id="pills-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="pills-requests-tab" data-toggle="pill"
          href="#pills-requests" role="tab" aria-controls="pills-requests"
          aria-selected="false">Friend Requests</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-users-tab" data-toggle="pill"
            href="#pills-users" role="tab" aria-controls="pills-users"
            aria-selected="true">Find Friends</a>
        </li>
      </ul>
    </div>
  </div>


  <div class="tab-content mt-4" id="pills-tabContent">

    <div class="tab-pane fade show active" id="pills-requests" role="tabpanel" aria-labelledby="pills-requests-tab">
      <div class="list-group shadow-sm mb-3">
        <% if current_user.requested_friends.any? %>
          <% current_user.requested_friends.each do |requesting_user| %>
            <div class="list-group-item">
              <%= link_to requesting_user.name, user_path(requesting_user), class: "h6 text-dark text-decoration-none" %>
              <%= link_to 'Accept Request', accept_path(requesting_user), class: "btn btn-sm btn-outline-primary float-right" %>
              <%= link_to 'Ignore Request', decline_path(requesting_user), class: "btn btn-sm btn-outline-secondary mr-2 float-right" %>
            </div>
          <% end %>
        <% else %>
        <div class="list-group-item">
          <span class="text-muted">No requests to review</span>
        </div>
        <% end %>
      </div>
    </div>

    <div class="tab-pane fade" id="pills-users" role="tabpanel" aria-labelledby="pills-users-tab">
      <div class="list-group shadow-sm mb-3">
        <% @users.each do |user| %>
          <% unless user == current_user %>
            <div class="list-group-item">
              <%= link_to user.name, user_path(user), class: "h6 text-dark text-decoration-none" %>
              <%= link_to 'Send Request', request_path(user),
                class: "btn btn-sm btn-outline-primary float-right" unless current_user.friends_with?(user) %>
              <%= link_to 'Unfriend', unfriend_path(user), class: "btn btn-sm btn-outline-primary float-right" if current_user.friends_with?(user) %>
              <% if current_user.pending_friends.include?(user) %>
                <span class="text-muted float-right mr-3">Waiting for reply</span>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1> <%= @user.name %> </h1>
  </div>
  <div class="col-md-6">
    <ul class="nav nav-pills mb-3 float-right" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="pills-timeline-tab" data-toggle="pill" href="#pills-timeline" role="tab" aria-controls="pills-timeline" aria-selected="true">Timeline</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-about-tab" data-toggle="pill" href="#pills-about" role="tab" aria-controls="pills-about" aria-selected="false">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-friends-tab" data-toggle="pill" href="#pills-friends" role="tab" aria-controls="pills-friends" aria-selected="false">Friends</a>
      </li>
    </ul>
  </div>
</div>


<div class="tab-content mt-4" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-timeline" role="tabpanel" aria-labelledby="pills-timeline-tab">
    <% if @user.posts.any? %>
      <% @user.posts.each do |post| %>
        <div class="card shadow-sm mt-3">
          <div class="card-body">
            <%= link_to post.user.name, user_path(post.user), class: "h5 d-inline text-dark text-decoration-none" %>
            <a class="float-right" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-h text-muted"></i>
            </a>
            <div class="dropdown-menu">
              <%= link_to 'Edit', edit_post_path(post), class: "dropdown-item" %>
              <%= link_to 'Delete', post_path(post), method: :delete, class: "dropdown-item",
                  data: { confirm: "Are you sure?"}%>
            </div>
            <p class="small"> <%= post.created_at.strftime('%b %e at %l:%M %p') %> </p>
            <p> <%= post.body %> </p>
            <hr>

            <% if post.likers.include?(current_user) %>
              <%= link_to unlike_post_path(post), class: "text-decoration-none text-dark" do %>
                <i class="fas fa-thumbs-up text-primary"></i> <%= pluralize(post.likers.count, 'like') %>
              <% end %>
            <% else %>
              <%= link_to like_post_path(post), class: "text-decoration-none text-dark" do %>
                <i class="far fa-thumbs-up"></i> <%= pluralize(post.likers.count, 'like') %>
                <% end %>
            <% end %>

            <%= link_to "#{pluralize(post.comments.count, 'comment')}", post_path(post),
            class: "text-muted float-right" %>
          </div>
        </div>
      <% end %>
    <% else %>
    <div class="list-group shadow-sm mb-3">
      <div class="list-group-item">
        <span class="text-muted"> No posts yet </span>
      </div>
    </div>
    <% end %>

  </div>
  <div class="tab-pane fade" id="pills-about" role="tabpanel" aria-labelledby="pills-about-tab">
    <div class="card shadow-sm">
      <div class="card-body">
        <h5>About</h5>
        <p>About will go here</p>
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-friends" role="tabpanel" aria-labelledby="pills-friends-tab">
    <div class="list-group shadow-sm mb-3">
      <% if @user.friends.any? %>
        <% @user.friends.each do |friend| %>
          <div class="list-group-item">
            <%= link_to friend.name, user_path(friend), class: "h6 text-dark text-decoration-none" %>
          </div>
        <% end %>
      <% else %>
      <div class="list-group-item">
        <span class="text-muted">No friends yet</span>
      </div>
      <% end %>
    </div>
  </div>
</div>